[package]
name = "Airi"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.14"
serde_json = "1.0.140"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.219", features = ["derive"] }
